[package]
name = "mdman"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
dirs = "6.0.0"
notify = "8.1.0"
notify-rust = "4.11.7"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
